pull_request_rules:

  - name: Automatically approve and merge Dependabot PRs
    conditions:
      - base=master
      - author=dependabot[bot]
      - status-success=Run Unit Tests
      - status-success=Semantic Pull Request
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
    actions:
      review:
        type: APPROVE
      merge:
        merge_bot_account: nikolaymatrosov
        method: squash

