name: 'Yandex Cloud CR "Login" Action for GitHub Actions'
description: 'Logs in the local Docker client to YC CR'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  yc-sa-json-credentials:
    required: false
    description: 'Json containing authorized key for Service Account. More info https://cloud.yandex.ru/docs/container-registry/operations/authentication#sa-json'
  yc-iam-token:
    required: false
    description: 'Token that can be used to authenticate in Yandex Container Registry. More info https://yandex.cloud/ru/docs/iam/concepts/authorization/iam-token'
  yc-sa-id:
    required: false
    description: 'Service account id to authorize using service account federation. More info https://yandex.cloud/ru/docs/iam/tutorials/wlif-github-integration'
  cr-endpoint:
    required: false
    description: 'Cloud API endpoint'
    default: 'cr.yandex'
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'
